$:
  push:
    - stages:
        - name: "Build Docker image"
          docker:
            build: ./Dockerfile.cnb
          runner:
            cpus: 2
            memory: 4G
  vscode:
    - docker:
        build: ./Dockerfile.cnb
        runner:
          cpus: 2
          memory: 2G
        services:
          - vscode
        stages:
          - name: "Start application"
            script: cd ai-news-backend && gunicorn -w 2 -k uvicorn.workers.UvicornWorker app.main:app --bind 0.0.0.0:7860
        ports:
          - "7860"