main:
  push:
    - stages:
        - name: "Build Docker image"
          docker:
            build: ./Dockerfile.cnb
          runner:
            cpus: 2
            memory: 4G
  run:
    - stages:
        - name: "Start application"
          docker:
            image: .
          ports:
            - "7860"
          runner:
            cpus: 2
            memory: 2G